name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "15 18 * * *" # 0315(JST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 9
